### ISSUE TITLE
crash when changing the order list

### ISSUE THREAD

**Issue by farvardin** [yoyz/audio#10]
I've compiled latest picoloop on my x86_64 computer, it works fine, but when I'm changing the pattern list in the L/S menu (bottom menu), with alt+arrow, it often crashes without reason. I get this kind of output in the console:

7fd9005bf000-7fd9005e2000 r-xp 00000000 08:05 9572647                    /lib/x86_64-linux-gnu/ld-2.19.so
7fd9005fe000-7fd90072a000 rw-s 00000000 00:05 104497184                  /SYSV00000000 (deleted)
7fd90072a000-7fd90072b000 ---p 00000000 00:00 0 
7fd90072b000-7fd9007be000 rw-p 00000000 00:00 0 
7fd9007d5000-7fd9007d8000 rw-p 00000000 00:00 0 
7fd9007d8000-7fd9007df000 r--s 00000000 08:05 6035999                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7fd9007df000-7fd9007e1000 rw-p 00000000 00:00 0 
7fd9007e1000-7fd9007e2000 r--p 00022000 08:05 9572647                    /lib/x86_64-linux-gnu/ld-2.19.so
7fd9007e2000-7fd9007e3000 rw-p 00023000 08:05 9572647                    /lib/x86_64-linux-gnu/ld-2.19.so
7fd9007e3000-7fd9007e4000 rw-p 00000000 00:00 0 
7ffc3b685000-7ffc3b6a6000 rw-p 00000000 00:00 0                          [stack]
7ffc3b790000-7ffc3b792000 r--p 00000000 00:00 0                          [vvar]
7ffc3b792000-7ffc3b794000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by yoyz** [comment]
Ok, weird, do you have this issue from "master" which is today above "picoloop-0.73" tag ?
If it is the case, could you do this : 
$ git log | head
And post me the output, it will tell me the last commit included in your build, so I can see where it is broken.


$ gdb ./PatternPlayer_debian_Rtaudio
(gdb) r
...
...
When the crash occur, gdb will give you back the prompt, then issue a : 
(gdb) bt
And post the bt output ( backtrace ).

Then if you have time, you can go in the past to tell me if it is from master, or beyond.
$ git tag
$ git checkout picoloop-0.73 ( or picoloop-0.72 )
Remove debianrtaudio directory, rebuild the soft and see if it crash.

Thank you

**Comment by farvardin** [comment]
Thank you, https://github.com/yoyz/audio/commit/61da20ce5b927da5c6018780030804bde24cc132 fixed this!
