### ISSUE TITLE
B3 before C3

### ISSUE THREAD

**Issue by farvardin** [yoyz/audio#15]
When we enter notes, it's like this: 

...G2, G2+, A2, A2+,**B3**,C3,C3+,D+... (and B4 is before C4 etc)

but it should be:

...G2, G2+, A2, A2+,**B2**,C3,C3+,D+...

actually, B3 sounds like B2 so it doesn't affect the replay, only the display.

**Comment by yoyz** [comment]
Should be fixed on master branch and picoloop-0.74c

**Comment by yoyz** [comment]
I close this one, reopen it if it doesn't work
